### ISSUE TITLE
Remove TOPEX Cal1 bias

### ISSUE THREAD

**Issue by remkos** [remkos/rads#112]
Following Backley et al. 2017, undo the range bias applied through the external range bias correction file.

**Comment by remkos** [comment]
Code created by commit efe9a4f91313b03c7dcedff45c132589f1f46708

**Comment by remkos** [comment]
All TOPEX data patched. Upload finished 30 Nov 2017.

**Comment by dallasmasters** [comment]
I noticed that the values of the cal1 bias that were recently removed in this update are dR_av_N (column 3) of the original Wallops correction table at https://topex.wff.nasa.gov/range-stability/. The original cal1 bias values applied to MGDR-B data were actually dR_av_T (column 5). This was confirmed in the last RGDR discussions. Should the cal1 bias values you removed actually be dR_av_T instead of dR_av_N?
