### ISSUE TITLE
Problems with radsstat

### ISSUE THREAD

**Issue by leuliett** [remkos/rads#171]
radsstat has two errors: 1) The maximum value is always nan and 2) the option --no-stddev suppresses the output from --minmax.

1) The commit 
https://github.com/remkos/rads/commit/57794bca779798a06cc5db48c094121de50928cd sets `z(:,1:) = nan`, which causes the max value to always be nan:

```
swift:~$ radsstat -Sj3 -l -C1 -c
# Statistics of RADS variables (box weight)
# Created: 2021-12-28 16:34:39 UTC: radsstat -Sj3 -l -C1 -c
#
# Satellite : j3/a
# Cycles    :    1 -    1
# Passes    :    1 -  254
#
# Output columns:
#    ( 1) cycle
#    ( 2) date at beginning of cycle [YYMMDD]
#    ( 3) nr of measurements
#    ( 4) mean time [seconds since 1985-01-01 00:00:00 UTC]
# ( 5- 8) mean, stddev, min and max of sea level anomaly [m]
  1 160217   540421  982747942.   0.04301   0.11024  -1.93600       NaN
```

2) The parameter --no-stddev introduced in commit https://github.com/remkos/rads/commit/95a7f35dab430e1f79ca510ca5161f2e8cefff89 also suppresses the output from --minmax.

```
swift:~$ radsstat -Sj3 -l -C1 -c --no-stddev
# Statistics of RADS variables (box weight)
# Created: 2021-12-28 16:36:33 UTC: radsstat -Sj3 -l -C1 -c --no-stddev
#
# Satellite : j3/a
# Cycles    :    1 -    1
# Passes    :    1 -  254
#
# Output columns:
#    ( 1) cycle
#    ( 2) date at beginning of cycle [YYMMDD]
#    ( 3) nr of measurements
#    ( 4) mean time [seconds since 1985-01-01 00:00:00 UTC]
#    ( 5) mean of sea level anomaly [m]
  1 160217   540421  982747942.   0.04301
```

**Comment by remkos** [comment]
I can confirm that both these bugs are present.

**Comment by remkos** [comment]
I think number 1 is not coming from the change referred to, but rather from the fact that the IEEE fortran standard, nor gfortran, clearly defines what the result of `max(x,y)` is when either or both `x` and `y` are Nan.

My experiments with gfortran shows that
- `max(NaN,x)` returns `NaN`
- `max(x,NaN)` returns `x`

In most RADS programs, xmin and xmax are first initialised as NaN and then updated using
```
xmin = min(xmin, x)
xmax = max(xmax, x)
```
This would mean that both `xmin` and `xmax` remain NaN. I do not understand why `xmin` does appear to be updated; potentially because of the undefined nature of the routine. Using the apparent implementation of `min` and `max` in gfortran, this could then be replaced by
```
xmin = min(x, xmin)
xmax = max(x, xmax)
```
But maybe better is to avoid the compiler-dependent implementation and go for:
```
if (.not.(x > xmin)) xmin = x
if (.not.(x < xmax)) xmax = x
```

**Comment by remkos** [comment]
Returning assignment to @leuliett to check implementation as per commits above and close this issue.

**Comment by leuliett** [comment]
Confirm that both issues are fixed by these commits.
