### ISSUE TITLE
Inconsistencies in Geoid EGM2008

### ISSUE THREAD

**Issue by ludwigus** [remkos/rads#193]
Hi,
I did a calibration of the reference missions (Topex, Jason, S6A) with ADT using the Geoid instead of MSS. As I found some unexpected biases, I analyzed the single parameters and noticed that the geoid seems to be responsible for this. Calculating global tandem offsets of the geoid_egm2008 parameter yields following mean values:
tx-j1:  1.2 cm
j1-j2:  0.0 cm
j2-j3: -1.2 cm
j3-6a: 0.0 cm
The same calculations with geoid_eigen6 or mss_dtu15 have always 0.0 cm mean. Did you apply geoid_egm2008 as a grid in RADS or is this parameter coming from the GDR? To me, my results imply that there is a global mean offset of 1.2 cm between the EGM2008 grid used for j1+j2 and the grid for tx,j3,6a.

I'm aware, that the tandem tracks can be a little shifted, resulting in geoid differences due to geoid gradients. However, in global average, this should not be as much as 1.2 cm. Furthermore, there is no such offset in MSS or EIGEN6, implying that this is not the source of this offset.

**Comment by leuliett** [comment]
Hi Ludwig,
For the standard RADS databases, geoid_egm2008 is computed from a 1-minute grid. In 2017 Remko changed the grid so that it would have a zero global mean. The previous grid did have a global mean with a 1.2 cm magnitude. The J1 and J2 databases have not been updated since the grid change. rads.xml could be modified to correct EGM2008 for the older missions until they are updated.

**Comment by remkos** [comment]
This is now fixed. The J1 and J2 databases have been updated with a newly interpolated values from the current EGM2008 grid.
