### ISSUE TITLE
Possible iono quality flag error in rads_gen_j2.f90 and rads_gen_j3.f90

### ISSUE THREAD

**Issue by leuliett** [remkos/rads#80]
Should these lines in rads_gen_j2.f90 and rads_gen_j3.f90:

```
    call nc2f ('qual_alt_1hz_range_ku_mle3',3)      ! bit  3: Quality dual-frequency iono
    call nc2f ('qual_alt_1hz_range_ku',3)           ! bit  3: Quality dual-frequency iono
```

check the "range_c" quality flags?

```
    call nc2f ('qual_alt_1hz_range_c_mle3',3)       ! bit  3: Quality dual-frequency iono
    call nc2f ('qual_alt_1hz_range_c',3)            ! bit  3: Quality dual-frequency iono
```

```
! Now do specifics for MLE3 (not used for the time being)

    flags_save = flags  ! Keep flags for later
    call nc2f ('qual_alt_1hz_range_ku_mle3',3)      ! bit  3: Quality dual-frequency iono
    call nc2f ('qual_alt_1hz_range_ku_mle3',11)     ! bit 11: Quality range
    call nc2f ('qual_alt_1hz_swh_ku_mle3',12)       ! bit 12: Quality SWH
    call nc2f ('qual_alt_1hz_sig0_ku_mle3',13)      ! bit 13: Quality Sigma0
    flags_mle3 = flags  ! Copy result for MLE3
    flags = flags_save  ! Continue with MLE4 flags

! Redo the last ones for MLE4

    call nc2f ('qual_alt_1hz_range_ku',3)           ! bit  3: Quality dual-frequency iono
    call nc2f ('qual_alt_1hz_range_ku',11)          ! bit 11: Quality range
    call nc2f ('qual_alt_1hz_swh_ku',12)            ! bit 12: Quality SWH
    call nc2f ('qual_alt_1hz_sig0_ku',13)           ! bit 13: Quality Sigma0

```

**Comment by remkos** [comment]
The line
`call nc2f ('qual_alt_1hz_range_c',3)            ! bit  3: Quality dual-frequency iono`
is already included in rads_gen_j2.f90 (line 196) and rads_gen_j3.f90 (line 197).
There is no equivalent variable qual_alt_1hz_range_c_mle3, since the there is also no range_c_mle3.

Consequently, no changes are needed.

**Comment by leuliett** [comment]
I'm still confused why line 220 in rads_gen_j2.f90
    call nc2f ('qual_alt_1hz_range_ku',3)           ! bit  3: Quality dual-frequency iono
seems to supersede line: 196:
    call nc2f ('qual_alt_1hz_range_c',3)            ! bit  3: Quality dual-frequency iono

**Comment by remkos** [comment]
Line 220 does not **supersede** line 196. It **adds** to it.
The idea is as follows:
Line 192: bit 3 of flags is unset
Line 196: set bit 3 when qual_alt_1hz_range_c is non-zero, leave as is (unset) otherwise.
Line 210: copy flags to flags_save
Line 211: set bit 3 when qual_alt_1hz_range_ku_mle3 is non-zero, leave as is otherwise.
Line 215: copy flags to flags_mle3
Line 216: return to flags_save (i.e. bit 3 may be set by qual_alt_1hz_range_c only.
Line 220: set bit 3 when qual_alt_1hz_range_ku is non-zero, leave as is otherwise.
Consequently, bit 3 of flags is set when **either** qual_alt_1hz_range_c or qual_alt_1hz_range_ku are non-zero, and bit 3 of flags_mle3 is set when **either** qual_alt_1hz_range_c or qual_alt_1hz_range_ku_mle3 is non-zero.
There is no qual_alt_1hz_range_c_mle3.
