### ISSUE TITLE
​ radsxolist --edit doesn't use default value

### ISSUE THREAD

**Issue by leuliett** [remkos/rads#85]
​The help implies that
radsxolist -e
should default to 
radsxolist -e 3.5
instead it returns
radsxolist: Option "-e radsxogen.nc" could not be parsed

**Comment by remkos** [comment]
This is again one of the cases where an "optional argument" to a command line option (-e in this case) comes to hunt/hurt us. You did not actually put nothing behind -e, you put radsxogen.nc. Thus the command line parser gets confused.

We can only resolve this if we require an option before the filename, for example -o. Then '-e -o radsxogen.nc' would not be misinterpreted.

A present workaround would be to put -e at the very end of the command line, of before another '-<something>'

Please suggest the solution that would work best for you.

**Comment by leuliett** [comment]
I'd suggest that we change the syntax to:
-e[=VAL]
so that this optional argument can be parsed before the filename...

**Comment by remkos** [comment]
Unfortunately, that would not resolve your problem, as "-e radsxogen.nc" still would fail. Also -e=5 or something is not standard practice. Maybe I should avoid these optional arguments to command line options altogether ...

**Comment by remkos** [comment]
There were only three solutions to this problem:
1. Ban all optional arguments from short options AND only allow them on long options AND force the = sign between the long option and its argument, so no more -e [VAL] or --edit [VAL], but only -e VAL, --edit, or --edit=VAL.
2. Require an option before the FILENAME argument, like -i or --input
3. Educate people to either put FILENAME before the options or put -- before FILENAME, both of which are already working.

Since (1) would make a radical change to the interface, and (2) is just an alternative for (3), and (3) was already working and supported, I chose to just make the -- "option terminator" more prominent.

I have to also add that I found no consistency even within GNU on how this is done. Some commands have optional arguments on both short and long options, some only have it on long options. Most seem to support both --arg=param and --arg param.

Although there appears to be no specific guideline on this, [getopt_long](http://linux.die.net/man/3/getopt_long) explicitly supports:
- optional arguments on both the short and long options;
- long options in the form --arg=param and --arg param;
- short options in the form -ofoo and -o foo;
- use of -- as option terminator.

RADS4 supports exactly the same, and therefore does not appear to be an anomaly. Clearly it is a fact of life that when using optional arguments, one needs to be careful with non-option arguments, like FILENAME and preferable prefix them by --.

So the working of RADS4 has not been changed, only the syntax statements have been updated.
